# .travis.yml
language: shell
os: windows
install:
  - choco install unity
cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE
scripts:
    - %UNITY_PATH%\Editor\Unity.exe -batchmode -executeMethod CIBuildScript.PerformBuild -quit
