# .travis.yml
language: cpp
os: windows
install:
  - choco install unity
cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE
jobs:
  include:
    - stage: build
      script: 
      - cmd.exe /C build.bat
    - stage: test
      script: test.bat
