# .travis.yml
language: shell
os: windows
install:
  - choco install unity
cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE
jobs:
  include:
    - stage: build
    script:
        - %UNITY_PATH%\Editor\Unity.exe -batchmode -executeMethod CIBuildScript.PerformBuild -quit
    - stage: test
    script:
        - %UNITY_PATH%\Editor\Unity.exe -batchmode -runTests -quit
