 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dir
       - run: choco install unity --version=2020.3.1 --params="'/InstallationPath:C:\Unity'"
       - run: dir "C:\Unity\Editor"
       - run:
           name: "Building App"
           command: C:\Unity\Editor\Unity.exe -batchmode -executeMethod CIBuildScript.PerformBuild -quit
           shell: cmd.exe

